use_frameworks!

target 'Logomotive_Example' do
  pod 'Logomotive', :path => '../'

   target 'UnitTests' do
     inherit! :search_paths

    pod 'Logomotive', :path => '../'
    
    pod 'Quick', :git => 'https://github.com/devdrey/Quick.git' #'~> 1.0'
    pod 'Nimble', '~> 5.0'
   end
end
